### ISSUE TITLE
can^t import models

### ISSUE THREAD

**Issue by StudioZAAK** [armory3d/armorpaint_docs#2]
hi just purchased armory paint - if i drag and drop a model (obj/fbx) there is an error message : 
Error: Accented / Special Characters in file path

alltough there are no special characters in file path

**Comment by luboslenco** [comment]
Hello @StudioZAAK, which OS are you on? Does file path like `C:\Assets\model.obj` work? (or similar on Linux). Is the file name itself also clear of special / accented characters? Apologizes for this issue, working on a fix.

**Comment by StudioZAAK** [comment]
hi @luboslenco after 20years on mac i'm on win 10 now :) C:\Assets\model.obj works! thanks for tipp!

**Comment by luboslenco** [comment]
Hoho, what a transition. I have opened a dedicated issue on the tracker at https://github.com/armory3d/armorpaint/issues/156, will post asap once fix is ready so there is no need for workarounds like this.. Thanks for support!
